include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - newpipe_repo/**
    - build/**
  errors:
    unnecessary_const: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
